# Generated by Django 2.0.7 on 2019-04-12 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('contact_no', models.CharField(default=None, max_length=12)),
                ('address', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('dob', models.DateField(help_text='format : YYYY-MM-DD', max_length=10)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=None, max_length=1)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], default=None, max_length=3)),
                ('contact_no', models.CharField(default=None, max_length=12)),
                ('reports', models.FileField(help_text='upload reports in PDF format', upload_to='')),
                ('address', models.TextField(default=None)),
                ('blood_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donate.BloodBank')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('dob', models.DateField(help_text='format : YYYY-MM-DD', max_length=10)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=None, max_length=1)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], default=None, max_length=3)),
                ('disease', models.CharField(max_length=200)),
                ('contact_no', models.CharField(default=None, max_length=12)),
                ('address', models.TextField(default=None)),
            ],
        ),
    ]
