# Generated by Django 2.0.7 on 2019-04-12 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='blood_bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='donate.BloodBank'),
        ),
    ]
