# Generated by Django 2.2 on 2019-04-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0003_auto_20190414_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='address',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], default=None, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='contact_no',
            field=models.CharField(default=None, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='dob',
            field=models.DateField(help_text='format : YYYY-MM-DD', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='reports',
            field=models.FileField(help_text='upload reports in PDF format', null=True, upload_to=''),
        ),
    ]
